SELECT m.PK_SINGLE_SOURCE FROM (
SELECT
  m.PK_SINGLE_SOURCE,

  MAX(CASE WHEN ma.FK_ATTRIBUTE = 99 THEN ma.TXT_VALUE END) attr99
  
  FROM PRESENTER2.TB_SINGLE_SOURCE m
  JOIN PRESENTER2.TA_ATTR_SNGL_SRC ma
    ON ma.FK_SINGLE_SOURCE = m.PK_SINGLE_SOURCE
  
  GROUP BY m.PK_SINGLE_SOURCE
  ORDER BY m.PK_SINGLE_SOURCE
) r 
  INNER JOIN PRESENTER2.TB_SINGLE_SOURCE m
    ON m.PK_SINGLE_SOURCE = r.PK_SINGLE_SOURCE

  WHERE UPPER(attr99) NOT IN (?,?)