SELECT m.PK_SINGLE_SOURCE FROM (
SELECT
  m.PK_SINGLE_SOURCE,
  MAX(CASE WHEN ma.FK_ATTRIBUTE = 99 THEN ma.TXT_VALUE END) attr99
  FROM CONNECTA.TB_SINGLE_SOURCE m
  JOIN CONNECTA.TA_ATTR_SNGL_SRC ma
    ON ma.FK_SINGLE_SOURCE = m.PK_SINGLE_SOURCE
  GROUP BY m.PK_SINGLE_SOURCE
  ORDER BY m.PK_SINGLE_SOURCE
) r
  INNER JOIN CONNECTA.TB_SINGLE_SOURCE m
    ON m.PK_SINGLE_SOURCE = r.PK_SINGLE_SOURCE
  WHERE attr99 = ?