-- Datasource que os testes de análise dependem
INSERT INTO CONNECTA.TB_DATASOURCE (PK_DATASOURCE, DS_DATASOURCE, NM_DATASOURCE, TP_DATASOURCE, TXT_SENHA, TXT_USUARIO)
    VALUES (CONNECTA.TB_DATASOURCE_SEQ.nextval, 'Descrição teste', 'Teste', 'TESTE', '123456', 'usuario');

-- Análise a ser buscada
INSERT INTO CONNECTA.TB_ANALYSIS (PK_ANALYSIS, DS_ANALYSIS, NM_ANALYSIS, TP_ANALYSIS, FK_DATASOURCE)
    VALUES (CONNECTA.TB_ANALYSIS_SEQ.nextval, 'Teste descricao', 'Teste', 'TESTE', 1);
-- Análise a ser editada
INSERT INTO CONNECTA.TB_ANALYSIS (PK_ANALYSIS, DS_ANALYSIS, NM_ANALYSIS, TP_ANALYSIS, FK_DATASOURCE)
    VALUES (CONNECTA.TB_ANALYSIS_SEQ.nextval, 'Teste descricao', 'Teste', 'TESTE', 1);
-- Análise a ser deletada
INSERT INTO CONNECTA.TB_ANALYSIS (PK_ANALYSIS, DS_ANALYSIS, NM_ANALYSIS, TP_ANALYSIS, FK_DATASOURCE)
    VALUES (99, 'Teste descricao', 'Teste', 'TESTE', 1);


-- SingleSource a ser editado
-- INSERT INTO CONNECTA.TB_SINGLE_SOURCE (PK_SINGLE_SOURCE, NM_SINGLE_SOURCE, DS_SINGLE_SOURCE)
--     VALUES(CONNECTA.TB_ANALYSIS_SEQ.nextval, 'Teste nome', 'Teste Descrição');